---
distFolder: public
setup:
  - name: Setup Hugo
    action: peaceiris/actions-hugo@v2
    properties:
      extended: true
      hugo-version: 0.78.1
build:
  name: Build project
  command: hugo --gc --minify -b $SITE_URL
  environment:
    SITE_URL: ${{ steps.project.outputs.site-url }}
